import { useState } from "react";
import { formatDOB, checkBirthday } from "../dob";
import { sortByDOB, sortByFirstName, sortByLastName } from "../sorting";
import { SortFieldButton } from "./sortfieldbutton";

/**
 * Table component generated by passed API 
 * data  with columns (first name, last name, residing country, and date of birth)
 * and determines whether birthday has passed as a column.
 * 
 * @param {*} data Table data
 * @returns JSX
 */
export function TableComponent(data) {
    console.log(data);
    const tableData = data.data.results; // Pull results array from API data
    const [sortMethod, setSortMethod] = useState(null); // {field, order (1 = asc, -1 = desc)}

    // Manages state and ordering logic for sortable columns
    const enableSort = field => {
        let order = 1;
        if (sortMethod != null && sortMethod.field == field && sortMethod.order == 1) {
            order = -1;
        }
        setSortMethod({field, order});
    }

    // Drive sorting for specified fields based and handoff to corresponding sorting algorithms (see import)
    if (sortMethod != null) {
        if (sortMethod.field == "first") {
            tableData.sort(sortByFirstName(sortMethod));
        } else if (sortMethod.field == "last") {
            tableData.sort(sortByLastName(sortMethod));
        } else if (sortMethod.field == "dob") {
            tableData.sort(sortByDOB(sortMethod));
        }
    }

    const today = new Date(); // Instantiate today's date once to reduce total memory use on iteration
    const tableRows = tableData.map((row, i) => {
        const dob = new Date(row.dob.date); // Build Date for DOB to aid in formatting and parsing
            return (
                <tr key={i} className="odd:bg-gray-800">
                    <td>{row.name.first}</td>
                    <td>{row.name.last}</td>
                    <td>{row.location.country}</td>
                    <td>{formatDOB(dob)}</td>
                    <td>{checkBirthday(dob, today)}</td>
            </tr>
        );
    });

    return (
        <div className="w-3/4 border rounded border-2 border-blue-600">
            <table className="w-full bg-gray-600 text-center">
                <thead className="border-b border-white">
                    <tr className="">
                        <th>
                            <SortFieldButton sortMethod={sortMethod} sortAction={enableSort} field="first">First Name</SortFieldButton>
                        </th>
                        <th>
                            <SortFieldButton sortMethod={sortMethod} sortAction={enableSort} field="last">Last Name</SortFieldButton>
                        </th>
                        <th>Country</th>
                        <th>
                            <SortFieldButton sortMethod={sortMethod} sortAction={enableSort} field="dob">Date of Birth</SortFieldButton>
                        </th>
                        <th>Birthday</th>
                    </tr>
                </thead>
                <tbody>
                    {/* Genereate the rows from API data */}
                    {tableRows}
                </tbody>
            </table>
        </div>
    )
}